type: google.api.Service
config_version: 3

http:
  rules:
    #################### DomainsExtractor ####################
    - selector: blockscout.bens.v1.DomainsExtractor.SearchAddress
      post: /api/v1/{chain_id}/domains:reverse-search
      body: "*"

    - selector: blockscout.bens.v1.DomainsExtractor.GetDetailedDomain
      get: /api/v1/{chain_id}/domains/{name}

    #################### Health ####################

    - selector: blockscout.ethBytecodeDb.v2.Health.Check
      get: /health
